<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/styles.css">
    <script src="https://kit.fontawesome.com/224143ea2d.js" crossorigin="anonymous"></script>
    <script src="/js/myScript.js"></script>
    <title>About</title>
    <link rel="icon" type="image/png" href="/imgs/code-pngrepo-com.png">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Sharing <img src="/imgs/code-pngrepo-com.png" alt="" style="height: 1em;"> Codes</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav mr-auto">
            <li><a class="nav-link" href="/code/latest">Recent codes</a></li>
            <li><a class="nav-link" href="/code/usage">Usage</a></li>
            <li><a class="nav-link" href="/code/about">About</a></li>
        </ul>
        <span class="navbar-text">
                <a href="https://github.com/nuromirzak/sharing-codes" target="_blank">
                    <i class="fa-brands fa-github fa-2xl" style="color: black"></i>
                </a>
            </span>
    </div>
</nav>

<div class="container p-3">
    <h1 class="display-6">Sharing Codes <a href="https://hyperskill.org/projects/130" target="_blank">(a Hyperskill Academy Project)</a></h1>
    <p>An application that allows users to create, share and access code online. Code snippets are stored in the database and deleted if time and/or viewing limits are triggered for them. You can find the source code <a href="https://github.com/nuromirzak/sharing-codes"
                                                                                                                                                                                                                            target="_blank">here.
    </a></p>
    <p>Technologies used:</p>
    <ul>
        <li>Apache (WebServer)</li>
        <li>Java (Backend)</li>
        <li>Gradle (Build)</li>
        <li>Spring Boot (MVC, Boot)</li>
        <li>Bootstrap (CSS)</li>
        <li>Freemarker (HTML template engine)</li>
        <li>highlight.js (Syntax highlighting for the Web)</li>
    </ul>
</div>


<script src="/js/jquery.slim.min.js"></script>
<script src="/js/bootstrap.bundle.min.js"></script>
</body>

</html>